apiVersion: v1
kind: ServiceAccount
metadata:
  name: quarkus-vs-sb-performance
  labels:
    app: quarkus-vs-sb-performance
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-vs-sb-performance
  annotations:
    app: quarkus-vs-sb-performance
  labels:
    app: quarkus-vs-sb-performance
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: quarkus-vs-sb-performance
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-vs-sb-performance
  annotations:
    app: quarkus-vs-sb-performance
  labels:
    app: quarkus-vs-sb-performance
spec:
  selector:
    matchLabels:
      app: quarkus-vs-sb-performance
  template:
    metadata:
      labels:
        app: quarkus-vs-sb-performance
    spec:
      serviceAccountName: quarkus-vs-sb-performance
      containers:
        - name: quarkus-vs-sb-performance
          image: image-name-here:image-tag-here
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health/live
              port: http
            initialDelaySeconds: 8
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/health/ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: quarkus-vs-sb-performance
                  key: dbUser
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quarkus-vs-sb-performance
                  key: dbPassword
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: quarkus-vs-sb-performance
                  key: dbHost
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: quarkus-vs-sb-performance
                  key: dbName
          resources:
            limits:
              cpu: 750m
              memory: 256Mi
            requests:
              cpu: 500m
              memory: 128Mi

