version: '3.8'
services:
  database:
    image: 'postgres:12.3'
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=performance-benchmark
      - POSTGRES_PASSWORD=performance-benchmark
      - POSTGRES_DB=performance-benchmark